Repository ra3xdh/qucsator_rf, pull requests merged in 2024-09, with the labels that each got.

#18 Remove software implementation in real.cpp and complex.cpp
  src/math/CMakeLists.txt
  src/math/complex.cpp
  src/math/complex.h
  src/math/real.cpp
  src/math/real.h
Labels: refactoring

#17 refactoring cmake
  CMakeLists.txt
  src/CMakeLists.txt
Labels: cmake, refactoring

#19 Simple TRAN models for mscorner, msmbend and bonwire
  src/components/microstrip/bondwire.cpp
  src/components/microstrip/bondwire.h
  src/components/microstrip/mscorner.cpp
  src/components/microstrip/mscorner.h
  src/components/microstrip/msmbend.cpp
  src/components/microstrip/msmbend.h
Labels: new feature
